### PR TITLE
[Unity] more elegant solution to unity detection

### PR DESCRIPTION
**Pull request by markbaas**
A proposed fix for https://github.com/atom/electron/issues/465

### CODE REVIEW

**Comment by markbaas** [comment]
I couldn't test it as I wasn't able to compile electron (tried all weekend).

**Comment by paulcbetts** [comment]
@markbaas The problem is that this isn't correct. Even if I'm running Xubuntu (i.e. not using Unity), we still need to operate as if we're under Ubuntu notifications

**Comment by markbaas** [comment]
Hmm in that case the fix just may be adding "/usr/lib/[arch]-linux-gnu/" to the path.

**Comment by paulcbetts** [comment]
@markbaas Yeah, we'll have to end up checking both places since not every distro will end up doing this right away. I'd certainly love to find a more thorough solution though

**Comment by deepak1556** [comment]
Cant we just try a dlopen with RTLD_NOLOAD to check for libunity instead ? chrome seems to be doing the same thing https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/ui/libgtk2ui/unity_service.cc&sq=package:chromium&l=73&rcl=1455582456

**Comment by paulcbetts** [comment]
@deepak1556 This would solve the path issue, yeah - good idea

**Comment by 3v1n0** [comment]
Looks good, but `XDG_CURRENT_DESKTOP` has to be handled as a `:`-separated list.

**Comment by paulcbetts** [comment]
I mentioned this earlier, but this isn't correct sadly - people using non-Unity DEs still have Unity's patched notifier, so they will get message boxes

**Comment by paulcbetts** [comment]
Thanks for having a go at this @markbaas, but it looks like we found a better way to do this in #210 that should fix the bug

**Pull request closed without merging**
